"""
Django settings for itreactor project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/
from pathlib import Path

# Build paths inside the project like this: str(BASE_DIR / 'subdir').
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    'itreactor.ru',
    '.itreactor.ru',
    'assets.itreactor.ru',
    'media.itreactor.ru',
]
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

# URL to use when referring to static files located in STATIC_ROOT.
# Example: "/static/" or "http://static.example.com/"
STATIC_URL = 'https://assets.itreactor.ru/'

# STATICFILES_DIRS is the list of folders where Django will search for additional static files aside
# from the static folder of each app installed.
# Note that these paths should use Unix-style forward slashes, even on Windows
# (e.g. "C:/Users/user/mysite/extra_static_content").
STATICFILES_DIRS = [
    str(BASE_DIR / "static")
]

# URL that handles the media served from MEDIA_ROOT, used for managing stored files.
# It must end in a slash if set to a non-empty value.
# Example: "http://media.example.com/"
MEDIA_URL = 'https://media.itreactor.ru/'

# MEDIA_ROOT is the folder where files uploaded using FileField will go.
# Absolute filesystem path to the directory that will hold user-uploaded files.
# Example: "/var/www/example.com/media/"
MEDIA_ROOT = str(BASE_DIR / "media")

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [str(BASE_DIR / "templates")],
        'APP_DIRS': True,
        'OPTIONS': {

            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': str(BASE_DIR / "db.sqlite3"),
    }
}