# Generated by Django 3.1.3 on 2021-01-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='company_address',
            field=models.CharField(default='', max_length=150, verbose_name='адрес компании'),
        ),
        migrations.AddField(
            model_name='website',
            name='company_email',
            field=models.CharField(default='', max_length=100, verbose_name='email компании'),
        ),
        migrations.AddField(
            model_name='website',
            name='company_name',
            field=models.CharField(default='', max_length=150, verbose_name='имя компании'),
        ),
        migrations.AddField(
            model_name='website',
            name='company_telegram',
            field=models.CharField(default='', max_length=100, verbose_name='телеграмм'),
        ),
        migrations.AddField(
            model_name='website',
            name='company_twitter',
            field=models.CharField(default='', max_length=100, verbose_name='твиттер'),
        ),
        migrations.AddField(
            model_name='website',
            name='company_vk',
            field=models.CharField(default='', max_length=100, verbose_name='вконтакте'),
        ),
        migrations.AddField(
            model_name='website',
            name='company_youtube',
            field=models.CharField(default='', max_length=100, verbose_name='ютуб'),
        ),
        migrations.AddField(
            model_name='website',
            name='contact_text',
            field=models.CharField(default='', max_length=500, verbose_name='контакты текст'),
        ),
    ]
