# Generated by Django 3.1.3 on 2021-01-08 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210105_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='company_address',
        ),
        migrations.RemoveField(
            model_name='website',
            name='company_email',
        ),
        migrations.RemoveField(
            model_name='website',
            name='company_name',
        ),
        migrations.AddField(
            model_name='website',
            name='contact_address',
            field=models.CharField(default='', max_length=150, verbose_name='contact: адрес'),
        ),
        migrations.AddField(
            model_name='website',
            name='contact_email',
            field=models.CharField(default='', max_length=100, verbose_name='contact: email'),
        ),
        migrations.AddField(
            model_name='website',
            name='contact_name',
            field=models.CharField(default='', max_length=150, verbose_name='contact: имя'),
        ),
        migrations.AddField(
            model_name='website',
            name='contact_phone',
            field=models.CharField(default='', max_length=20, verbose_name='contact: телефон'),
        ),
        migrations.AlterField(
            model_name='website',
            name='company_telegram',
            field=models.CharField(default='', max_length=100, verbose_name='info: телеграмм'),
        ),
        migrations.AlterField(
            model_name='website',
            name='company_twitter',
            field=models.CharField(default='', max_length=100, verbose_name='info: твиттер'),
        ),
        migrations.AlterField(
            model_name='website',
            name='company_vk',
            field=models.CharField(default='', max_length=100, verbose_name='info: вконтакте'),
        ),
        migrations.AlterField(
            model_name='website',
            name='company_youtube',
            field=models.CharField(default='', max_length=100, verbose_name='info: ютуб'),
        ),
        migrations.AlterField(
            model_name='website',
            name='contact_text',
            field=models.CharField(default='', max_length=500, verbose_name='contact: текст'),
        ),
    ]
