# Generated by Django 3.1.3 on 2021-01-08 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20210108_2333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website',
            old_name='company_telegram',
            new_name='contact_telegram',
        ),
        migrations.RenameField(
            model_name='website',
            old_name='company_twitter',
            new_name='contact_twitter',
        ),
        migrations.RenameField(
            model_name='website',
            old_name='company_vk',
            new_name='contact_vk',
        ),
        migrations.RenameField(
            model_name='website',
            old_name='company_youtube',
            new_name='contact_youtube',
        ),
    ]
