# Generated by Django 3.1.3 on 2020-12-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201206_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='tips',
            name='big',
            field=models.BooleanField(default=False, verbose_name='особый'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tips',
            field=models.ManyToManyField(to='blog.Tips', verbose_name='ключевые слова'),
        ),
    ]
