# Generated by Django 3.1.3 on 2020-12-06 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201206_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tips',
            name='big',
        ),
    ]
